# Copyright (c) OpenMMLab. All rights reserved.
import os
from concurrent import futures as futures
from os import path as osp

import mmengine
import numpy as np


class ScanNetData(object):
    """ScanNet data.
    Generate scannet infos for scannet_converter.

    Args:
        root_path (str): Root path of the raw data.
        split (str, optional): Set split type of the data. Default: 'train'.
        scannet200 (bool): True for ScanNet200, else for ScanNet.
        save_path (str, optional): Output directory.
    """

    def __init__(self, root_path, split='train', dataset="scannet", save_path=None):
        self.root_dir = root_path
        self.save_path = root_path if save_path is None else save_path
        self.split = split
        self.split_dir = osp.join(root_path)
        self.dataset = dataset
        if self.dataset == 'scannetpp':
            self.classes = [
                "wall",
            "ceiling",
            "floor",
            "door",
            "table",
            "cabinet",
            "ceiling lamp",
            "curtain",
            "chair",
            "blinds",
            "storage cabinet",
            "bookshelf",
            "office chair",
            "window",
            "whiteboard",
            "ceiling light",
            "fake ceiling",
            "monitor",
            "shelf",
            "object",
            "window frame",
            "pipe",
            "structure",
            "box",
            "heater",
            "kitchen cabinet",
            "storage rack",
            "sofa",
            "bed",
            "shower wall",
            "doorframe",
            "door frame",
            "roof",
            "wardrobe",
            "pillar",
            "plant",
            "blanket",
            "machine",
            "windowsill",
            "linked retractable seats",
            "window sill",
            "cardboard box",
            "tv",
            "books",
            "desk",
            "computer tower",
            "kitchen counter",
            "trash can",
            "trash bin",
            "jacket",
            "electrical duct",
            "blackboard",
            "cable tray",
            "air duct",
            "sink",
            "carpet",
            "bag",
            "counter",
            "refrigerator",
            "picture",
            "pillow",
            "cupboard",
            "window blind",
            "towel",
            "beam",
            "office table",
            "stool",
            "suitcase",
            "backpack",
            "bathtub",
            "rug",
            "keyboard",
            "rack",
            "gym mat",
            "toilet",
            "suspended ceiling",
            "shower floor",
            "clothes",
            "pipe storage rack",
            "air conditioner",
            "fume hood",
            "printer",
            "blind",
            "poster",
            "experiment bench",
            "electrical control panel",
            "shower curtain",
            "windowframe",
            "book",
            "ceiling beam",
            "painting",
            "paper",
            "ladder",
            "laboratory bench",
            "bench",
            "milling machine",
            "microwave",
            "partition",
            "board",
            "office cabinet",
            "rolling cart",
            "laboratory cabinet",
            "crate",
            "raised floor",
            "electrical panel",
            "mattress",
            "bottle",
            "pedestal fan",
            "sofa chair",
            "headboard",
            "fridge",
            "bucket",
            "kitchen unit",
            "beanbag",
            "construction materials",
            "oven",
            "pipes",
            "cushion",
            "power socket",
            "office desk",
            "whiteboards",
            "lab equipment",
            "shoes",
            "work bench",
            "file cabinet",
            "mirror",
            "basket",
            "beverage crate",
            "washing machine",
            "shoe rack",
            "hydraulic press",
            "photocopy machine",
            "telephone",
            "lab machine",
            "joined tables",
            "sliding door",
            "tv stand",
            "objects",
            "couch",
            "coat",
            "open cabinet",
            "scientific equipment",
            "coffee table",
            "garage door",
            "bin",
            "radiator",
            "standing lamp",
            "stove",
            "roller blinds",
            "fume cupboard",
            "pc",
            "stairs",
            "medical appliance",
            "closet",
            "trolley",
            "file folder",
            "projector",
            "cloth",
            "conference table",
            "cardboard",
            "blind rail",
            "dishwasher",
            "room divider",
            "copier",
            "ventilation pipe",
            "bathroom cabinet",
            "laptop",
            "electrical box",
            "arm chair",
            "bar counter",
            "stage",
            "ceiling ventilator",
            "lounge chair",
            "plant pot",
            "bathroom stall",
            "pinboard",
            "false ceiling",
            "comforter",
            "3d printer",
            "steel beam",
            "projector screen",
            "electric duct",
            "cart",
            "air pipe",
            "training equipment",
            "floor mounted air conditioner",
            "tile wall",
            "glass wall",
            "exhaust fan",
            "vacuum cleaner",
            "ceiling lights",
            "laundry basket",
            "nightstand",
            "armchair",
            "drying rack",
            "indoor crane",
            "storage trolley",
            "dresser",
            "l-shaped sofa",
            "coat hanger",
            "dining chair",
            "office visitor chair",
            "interactive board",
            "hose",
            "light switch",
            "shower ceiling",
            "coffee machine",
            "cables",
            "floor lamp",
            "fan",
            "wire tray",
            "compressor",
            "laboratory equipment",
            "dining table",
            "speaker",
            "climbing wall",
            "light",
            "paper towel dispenser",
            "coat rack",
            "table lamp",
            "frame",
            "duvet",
            "fire extinguisher",
            "range hood",
            "high table",
            "backdrop",
            "ventilation duct",
            "papers",
            "seat",
            "tablecloth",
            "electrical cabinet",
            "ping pong table",
            "bathroom floor",
            "ceiling pipe",
            "bedside table",
            "coffee maker",
            "computer desk",
            "urinal",
            "loft bed",
            "air vent",
            "chairs",
            "bedsheet",
            "television",
            "lamp",
            "rolling chair",
            "wall cabinet",
            "book shelf",
            "brick wall",
            "treadmill",
            "vent",
            "shirt",
            "canopy bed",
            "clothes hanger",
            "kettle",
            "cardboards",
            "shoe",
            "high stool",
            "tripod",
            "bar stool",
            "exhaust duct",
            "wooden plank",
            "squat rack",
            "cubicle door",
            "folding screen",
            "kitchen sink",
            "container",
            "bottles",
            "ottoman",
            "bicycle",
            "staircase railing",
            "overhead projector",
            "surfboard",
            "folder",
            "power strip",
            "high bench",
            "wall beam",
            "pallet cage",
            "interactive whiteboard",
            "floor sofa",
            "duct",
            "flat panel display",
            "wooden frame",
            "folding room divider",
            "cable",
            "mug",
            "rolling table",
            "locker",
            "standing banner",
            "decoration",
            "clothes drying rack",
            "foosball table",
            "standing poster",
            "bath tub",
            "yoga mat",
            "microscope",
            "paper bag",
            "mouse",
            "umbrella",
            "medical machine",
            "smoke detector",
            "cup",
            "cutting board",
            "console",
            "drum",
            "bathroom counter",
            "toilet paper",
            "robot car",
            "exhaust pipe",
            "bath cabinet",
            "whiteboard stand",
            "electrical control panels",
            "notice board",
            "paper towel",
            "crates",
            "bed frame",
            "bathroom mat",
            "shower partition",
            "cloth hangers",
            "clothes cabinet",
            "tv screen",
            "babyfoot table",
            "rolling curtain",
            "coat stand",
            "kitchen towel",
            "plank",
            "side table",
            "storage shelf",
            "mat",
            "shower",
            "white board",
            "information board",
            "backsplash",
            "guitar",
            "cloth rack",
            "ceiling vent",
            "partition wall",
            "kitchen shelf",
            "banner",
            "file binder",
            "cleaning trolley",
            "racing simulator",
            "workbench",
            "pot",
            "ac system",
            "power panel",
            "desk lamp",
            "broom",
            "wall /other room",
            "cpu",
            "fitted wardrobe",
            "tote bag",
            "plumbing pipe",
            "slippers",
            "blackboard frame",
            "magazine",
            "hose pipe",
            "rolled paper",
            "sweater",
            "clock",
            "tray",
            "desk fan",
            "vaccum cleaner",
            "projection curtain",
            "freezer display counter",
            "pan",
            "vase",
            "glass",
            "folders",
            "tap",
            "wall lamp",
            "plate",
            "laptop stand",
            "small cabinet",
            "file organizer",
            "clothes dryer",
            "wall painting",
            "paper towels",
            "curtain rail",
            "wheelchair",
            "bottle crate",
            "sheet",
            "folding sofa",
            "shower pan",
            "plastic case",
            "christmas tree",
            "piano",
            "ottoman chair",
            "jar",
            "foldable closet",
            "notebook",
            "calendar",
            "janitor cart",
            "storage box",
            "rolling blinds",
            "bathroom shelf",
            "soap dispenser",
            "binder",
            "wooden planks",
            "copy machine",
            "rice cooker",
            "gym mattress",
            "car door",
            "table football",
            "bowl",
            "light panel",
            "tissue box",
            "bedframe",
            "wall hanging",
            "jug",
            "skylight",
            "ceiling fan",
            "dish rack",
            "shelving cart",
            "instant pot",
            "whiteboard eraser",
            "floor mat",
            "socket",
            "mini fridge",
            "wall clock",
            "boots",
            "barbecue grill",
            "paper shredder",
            "file rack",
            "floor scrubber",
            "metal board",
            "water heater",
            "tool rack",
            "recliner",
            "barber chair",
            "ventilator",
            "trolley table",
            "standing fan",
            "water filter",
            "shoes holder",
            "wood planks",
            "vr setup",
            "trashcan",
            "bike",
            "lab materials",
            "wooden pallet",
            "dustbin",
            "curtain rod",
            "reflection",
            "toilet brush",
            "exercise ball",
            "air purifier",
            "kitchen back splash",
            "paper rack",
            "toolbox",
            "monitor cover",
            "file",
            "surfsuit",
            "ceiling cables",
            "night stand",
            "paper organizer",
            "serving trolley",
            "phone",
            "canvas",
            "camping bed",
            "tower pc",
            "cylinder",
            "magazine stand",
            "toy",
            "slipper",
            "air conditioning",
            "hanger",
            "vertical blinds",
            "desk organizer",
            "guitar bag",
            "spray bottle",
            "suit cover",
            "toaster",
            "spotlight",
            "machine container",
            "foot rest",
            "shopping trolley",
            "decoration piece",
            "control panel",
            "multifunction printer",
            "jerry can",
            "window head",
            "cooker hood",
            "basin",
            "panel",
            "papasan chair",
            "tv mount",
            "toilet seat",
            "shopping bag",
            "photocopier",
            "tube",
            "studio light",
            "stuffed toy",
            "cord cover",
            "power cabinet",
            "power cables",
            "filer organizer",
            "garage shelf",
            "jackets",
            "files",
            "luggage",
            "gym bag",
            "exhaust hood",
            "microwave oven",
            "floor cushion",
            "easy chair",
            "bar table",
            "shoe cabinet",
            "paper tray",
            "lab coat",
            "toilet paper dispenser",
            "kitchen storage rack",
            "equipment",
            "computer table",
            "mouse pad",
            "drawer",
            "headphones",
            "boxes",
            "bathroom sink",
            "outlet",
            "toaster oven",
            "tv table",
            "bedside cabinet",
            "rolling trolley",
            "step stool",
            "trousers",
            "bathroom rack",
            "shelf trolley",
            "glass shelf",
            "fabric",
            "lab fridge",
            "ceiling lamps",
            "work station",
            "barrel",
            "mop",
            "deck chair",
            "bath counter",
            "helmet",
            "standing clothes hanger",
            "garbage bin",
            "study table",
            "air fryer",
            "plastic bag",
            "oven range",
            "headphone",
            "kitchen counter top",
            "clothes rack",
            "wall unit",
            "grab bar",
            "flipchart",
            "scarf",
            "labcoat",
            "hat",
            "bedside lamp",
            "sewing machine table",
            "shower head",
            "dishes",
            "switchboard cabinet",
            "flip paper",
            "storage container",
            "canister",
            "wall board",
            "shower rug",
            "plastic box",
            "stovetop",
            "information stand",
            "footstool",
            "pack",
            "push cart",
            "table cloth",
            "celing lamp",
            "cupoard",
            "jeans",
            "smoke alarm",
            "beverage crates",
            "mattresses",
            "bath mat",
            "softbox",
            "whiteboard mount",
            "paper cutter",
            "plates",
            "cable raceway",
            "water kettle",
            "pictures",
            "pelican case",
            "towel rack",
            "rolling shelf cart",
            "built-in shelf",
            "documents",
            "equipment cover",
            "television stand",
            "bags",
            "sheets",
            "small dresser",
            "light stand",
            "beach umbrella",
            "faucet",
            "bagpack",
            "dumbbell",
            "water dispenser",
            "paper trays",
            "flowers",
            "tube lights",
            "medicine cabinet",
            "tv console",
            "mirror frame",
            "chandelier",
            "pen holder",
            "messenger bag",
            "ball",
            "glass bottle",
            "power sockets",
            "softbox light",
            "gym ball",
            "briefcase",
            "plastic bottle",
            "monitor stand",
            "human skeleton",
            "podium",
            "wall strip",
            "rods",
            "tablet",
            "bedside shelf",
            "headrail",
            "sink counter",
            "doormat",
            "baseboard",
            "bulletin board",
            "electric hob",
            "bean bag",
            "high pressure cylinder",
            "portable fan",
            "flush button",
            "wooden post",
            "lectern",
            "curtain frame",
            "computer monitor",
            "folding chair",
            "tabletop",
            "led ceiling fan",
            "high chair",
            "grill",
            "metal rack",
            "air conditioner tower",
            "sliding door frame",
            "cable rack",
            "drawers",
            "bench press",
            "ironing board",
            "wooden palette",
            "kitchenware",
            "blind rails",
            "plastic container",
            "curtain rails",
            "weighing scale",
            "headset",
            "tree trunk",
            "shower screen",
            "wall shelf",
            "watering can",
            "tool box",
            "file shelves",
            "bed sheet",
            "glass pane",
            "tower fan",
            "switch",
            "notice",
            "sack",
            "table mat",
            "flower pot",
            "dog bed",
            "laundry hanger",
            "mobile tv stand",
            "magazines",
            "file holder",
            "floor couch",
            "tv trolley",
            "chopping board",
            "centrifuge",
            "tubelight",
            "bedpost",
            "step",
            "center table",
            "upholstered bench",
            "sink pipe",
            "door mat",
            "storage bin",
            "towel radiator",
            "shower tray",
            "filefolders",
            "rolled papers",
            "electronic appliance",
            "boiler",
            "food container",
            "cable pathway",
            "carboard box",
            "metal sheet",
            "hand bag",
            "sign",
            "laundry rack",
            "screen",
            "cardbox",
            "fireplace surround",
            "boot",
            "envelope",
            "stools",
            "carton",
            "tool organizer",
            "kitchen utensils",
            "wall hooks",
            "paper roll",
            "water bottle",
            "shoe changing stool",
            "balcony door",
            "espresso machine",
            "water pipe",
            "trash cans",
            "recesssed shelf",
            "drum set",
            "skiboard",
            "speaker stand",
            "kitchen wall",
            "suit",
            "photo",
            "globe",
            "spice rack",
            "bulletin boards",
            "delivery bag",
            "router",
            "rolling blind",
            "easel",
            "shower cubicle",
            "dish drainer",
            "doorway",
            "folded table",
            "pants",
            "computer",
            "stuffed animal",
            "office chair",
            "cable conduit",
            "picture frame",
            "shoe stool",
            "recessed shelve",
            "toilet paper holder",
            "panelboard",
            "stapler",
            "skateboard",
            "workshop tool",
            "projector holder",
            "flag",
            "chemical canister",
            "web cam",
            "hoodie",
            "towel heater",
            "towel warmer",
            "shower curtain rod",
            "shower faucet",
            "water pipes",
            "shower door",
            "laboratory power supply",
            "tool",
            "ventilation",
            "soap bottle",
            "bathrobe",
            "pictures board",
            "cap",
            "woofer",
            "tshirt",
            "rolling bag",
            "shoe box",
            "luggage bag",
            "file storage",
            "cat bed",
            "stack of paper",
            "surfing board",
            "electric kettle",
            "rolling stand",
            "cover",
            "main switchboard",
            "pressure cooker",
            "stepladder",
            "countertop",
            "flip flops",
            "short table",
            "sit-up pillow",
            "duffel bag",
            "shower seating",
            "washbasin",
            "teddy bear",
            "stair",
            "plate rack",
            "ornament",
            "jerrycan",
            "filter jug",
            "t shirt",
            "cooking pot",
            "platform trolley",
            "blinds rod",
            "hand shower",
            "power socket unit",
            "sheep doll",
            "laptop bag",
            "game console",
            "bottles case",
            "lid",
            "dumbbell case",
            "rolled blanket",
            "paper stapler",
            "kitchen pot",
            "charcoal bag",
            "laundry hamper",
            "rolled poster",
            "bath towel",
            "apron",
            "dustpan",
            "trash bag",
            "document tray",
            "camera",
            "mirror cabinet",
            "dish drying rack",
            "gas tank",
            "cable roller",
            "case",
            "ring light",
            "hair dryer",
            "gym plate",
            "hand towel",
            "sill",
            "sidetable",
            "vice",
            "bench stool",
            "billboard",
            "rolling cabinet",
            "shower sink",
            "cloth piece",
            "oscilloscope",
            "condiments",
            "magazine rack",
            "wash basin",
            "cable panel",
            "photo frame",
            "tv receiver",
            "stand",
            "milk jug",
            "wooden board",
            "bladeless fan",
            "door frame",
            "wall paper",
            "scale",
            "purse",
            "electronic device",
            "sofa cushion",
            "sponge",
            "dish washer",
            "crate trolley",
            "tools",
            "kitchen hood",
            "laundry vent",
            "medical stool",
            "exhaustive fan",
            "portable ladder",
            "chemical container",
            "toilet paper rolls",
            "rag",
            "blender",
            "window pane",
            "dog bowl",
            "shopping basket",
            "piano stool",
            "electric box",
            "wall calendar",
            "paper holder",
            "chemical bottle",
            "coat hangers",
            "sandals",
            "foreman grill",
            "guitar case",
            "heater tube",
            "running shoes",
            "shower tap",
            "cloth hanger",
            "microphone",
            "cabinet frame",
            "decorative object",
            "light fixture",
            "paintings",
            "ceiling lamp bar",
            "paperbag",
            "chemical barrel",
            "wicker basket",
            "exit sign",
            "bottles rack",
            "water jug",
            "bottle carrier",
            "laboratory pellet press",
            "mini oven",
            "shower arm",
            "paper tube",
            "suitcase stand",
            "table fan",
            "shelve",
            "full-length mirror",
            "wood piece",
            "can",
            "suit bag",
            "water bubbler",
            "cushions",
            "first aid kit",
            "kitchen robot",
            "toilet flush button",
            "pillow toy",
            "plush doll",
            "styrofoam box",
            "document organizer",
            "pet carrier",
            "folding table",
            "gloves",
            "pitcher",
            "cable spool",
            "dumbbells",
            "rolled cable",
            "folding umbrella",
            "robot vacuum cleaner",
            "tower ventilator",
            "brush",
            "planter",
            "baseball cap",
            "gas cylinder",
            "paper files",
            "stereo",
            "baby stroller",
            "posters",
            "notebooks",
            "water bucket",
            "rucksack",
            "shower door frame",
            "drone",
            "kitchen cloth",
            "hand soap dispenser",
            "pegboard",
            "alarm",
            "emergency light",
            "sign board",
            "spice jars",
            "weight plate",
            "rolled projection screen",
            "keyboards",
            "laptop table",
            "hole puncher",
            "mixer",
            "piano chair",
            "paper bin",
            "wooden stick",
            "anti splatter shield",
            "fireplace",
            "rolled backdrop",
            "mousepad",
            "long pillow",
            "bananas",
            "column",
            "cd player",
            "eraser",
            "laptop sleeve",
            "hairdryer",
            "seat cushion",
            "plant pot mat",
            "wastebin",
            "wood panel",
            "detergent bottle",
            "safe box",
            "pouch",
            "blind rod",
            "mop basin",
            "plug",
            "document holder",
            "railing",
            "towels",
            "cutting boards",
            "plastic drum",
            "stack of tyres",
            "cat tree",
            "mirror light",
            "kettlebell",
            "chart",
            "dust pan",
            "sandal",
            "first aid cabinet",
            "bracket",
            "wire",
            "scooter",
            "racing wheel",
            "wine rack",
            "belt",
            "tissue dispenser stand",
            "towel paper dispenser",
            "air heater",
            "plushie",
            "knife set",
            "iron",
            "intercom",
            "kitchen ceiling",
            "package",
            "toilet paper dispensor",
            "sneakers",
            "umbrella stand",
            "egg carton",
            "organizer",
            "stick",
            "shampoo bottle",
            "cone",
            "pile of papers",
            "file tray",
            "wooden plan",
            "cooking pan",
            "brief",
            "paper towel package",
            "glove dispenser",
            "dispenser bottle",
            "kitchen drawer",
            "remote control",
            "powerstrip",
            "emergency shower",
            "scanner",
            "towel holder",
            "vr headset",
            "watering pot",
            "soda machine",
            "pole stand",
            "paper towel rolls",
            "roomba",
            "rolling mat",
            "fluorescent lamp",
            "flower",
            "pc tower",
            "metal mount",
            "oven gloves",
            "soap",
            "flush tank",
            "notepad",
            "pull up bar",
            "loafers",
            "water meter cover",
            "plastic tray",
            "webcam",
            "barbell",
            "tea pot",
            "wall hanger",
            "cabinet base panel",
            "laptop case",
            "paper towel holder",
            "skeleton",
            "socket extender",
            "extension chord reel",
            "wooden crate",
            "guillotine paper cutter",
            "sewing machine",
            "model car",
            "bed cover",
            "storage",
            "freezer",
            "piano book",
            "wifi router",
            "overhead shower",
            "chrismas tree",
            "drill",
            "clothes drying stand",
            "dumbell",
            "cabel",
            "badminton racket",
            "cool box",
            "thermostat",
            "dartboard",
            "switchboard cover",
            "candle",
            "electric stove",
            "paper ram",
            "notes",
            "insulated can",
            "prosthetic leg",
            "desk power strip",
            "utensils",
            "closet rail",
            "water pitcher",
            "plate weights",
            "extension cord",
            "toilet papers",
            "tea box",
            "tissue",
            "sauce pan",
            "postcards",
            "toothbrush",
            "floor mats",
            "frying pan",
            "package of paper",
            "microphone stand",
            "socket box",
            "leather mattress",
            "plastic can",
            "garbage bin cover",
            "plush toy",
            "electric guitar",
            "weight scale",
            "fruit",
            "tape dispenser",
            "pallet",
            "emergency kit",
            "bathroom mirror",
            "cloths",
            "door lamp",
            "power extension",
            "electric circuit board",
            "oven panel",
            "electrical pipe",
            "wall mounts",
            "shade",
            "photoframe",
            "file stack",
            "pizza box",
            "tennis racket",
            "wall hook",
            "recycle bag",
            "recessed shower shelve",
            "wall mounted telephone",
            "facsimile",
            "kitchen roll",
            "milk cartons",
            "totebag",
            "floor cleaner",
            "body weight scale",
            "stuffed animal door insulator",
            "wooden shelves",
            "neck pillow",
            "basketball",
            "cable wheel",
            "door vent",
            "foot massager",
            "pumper",
            "hanging light fixture",
            "interphone",
            "paper towel roll",
            "control unit",
            "folder oragnizer",
            "hanging frame",
            "paper stack",
            "door handle",
            "mini shelf",
            "beverage carton",
            "wok pan",
            "bedside counter",
            "bar",
            "pot lid",
            "radio",
            "paper box",
            "stabilizer",
            "headphone case",
            "folded cardboard box",
            "coaster",
            "pen tray",
            "marker",
            "shower mat",
            "rod",
            "device",
            "electric pot",
            "mixer machine",
            "barstool",
            "bread toaster",
            "electric mixer",
            "wall cord cover",
            "camera bag",
            "charger",
            "knife",
            "metal frame",
            "folded bag",
            "conduit pipe",
            "french press",
            "cabinet side panel",
            "cosmetic bag",
            "surveillance camera",
            "bathroom holder",
            "footrest",
            "glasses case",
            "handbag",
            "cooling pad",
            "flip flop",
            "game controller",
            "packet of toilet paper",
            "cable duct",
            "toilet paper roll",
            "monitor support",
            "fire alarm",
            "kitchen stove",
            "key hanger",
            "tub",
            "network socket",
            "ceilng light",
            "christmas ornament",
            "pepper mill",
            "wall outlet",
            "light cover",
            "caution board",
            "heels",
            "package bag",
            "blinds rail",
            "candle holder",
            "electric toothbrush",
            "pens",
            "tool case",
            "toilet flush",
            "wooden brush",
            "hand washing soap",
            "hygiene product",
            "water tap",
            "cosmetic pouch",
            "mount",
            "brushes",
            "knife holder",
            "dustpan and brush",
            "circular tray",
            "shoe case",
            "ar tag",
            "flipflop",
            "sculpture",
            "recycle bin",
            "kitchen utensil",
            "multiplug",
            "beaker stand",
            "chessboard",
            "pen",
            "toothpaste",
            "tv remote",
            "floor wiper",
            "wire hider",
            "water meter",
            "magazine holder",
            "mailbox",
            "paper file",
            "wall coat hanger",
            "utensil holder",
            "detergent",
            "safe",
            "packet",
            "dvd",
            "apples",
            "dvd player",
            "tupperware",
            "electrical board",
            "radiator pipe",
            "plat",
            "decorative mirror",
            "telephone stand",
            "water boiler",
            "cutboard",
            "hanging deer skull",
            "file orginizer",
            "satchel",
            "head model",
            "parcel",
            "dish soap bottle",
            "glass plate",
            "pencil case",
            "cleaning mop",
            "mixer glass",
            "joystick",
            "vacuum flask",
            "bag of oranges",
            "pencil holder",
            "pamphlet",
            "rope",
            "cd",
            "knife stand",
            "pencil cup",
            "binding machine",
            "grill pan",
            "tape",
            "cabinet top panel",
            "cutti̇ng board",
            "salad spinner",
            "water filter jug",
            "mop cloth",
            "sticky notes",
            "shower valve",
            "laptop cover",
            "running shoe",
            "toy models",
            "alligator clips",
            "insulated coffee mug",
            "pencil stand",
            "action figure",
            "desk light",
            "midi controller",
            "bathroom slippers",
            "elephant decoration piece",
            "switchboard",
            "remote",
            "arch folder",
            "power cord",
            "hot bag",
            "pencils cup",
            "knife block",
            "thermos",
            "power switch",
            "toothbrush holder",
            "cleaning liquid",
            "power board",
            "pull-up bar",
            "sandwich maker",
            "statue",
            "brief case",
            "airdyer",
            "bike helmet",
            "mirror lamp",
            "tennis rackets",
            "paint jar",
            "citrus juicer",
            "scissors",
            "hanging hook",
            "napkin",
            "laundry detergent",
            "disinfectant dispenser",
            "cleaning brush",
            "food",
            "pan set",
            "kitchen appliance",
            "mop pad",
            "dish soap",
            "plunger",
            "paper package",
            "plastic mat",
            "calculator",
            "voltage stabilizer",
            "whiteboard marker",
            "wall coat rack",
            "milk carton",
            "cosmetic bottle",
            "shower handle",
            "tissue paper",
            "shorts",
            "game console controller",
            "remote controller",
            "teapot",
            "drain",
            "juice box",
            "phone stand",
            "soap container",
            "flush",
            "rubber water bag",
            "shower gel",
            "envelopes",
            "snack bag",
            "watering bucket",
            "first aid box",
            "banana",
            "paper notebook",
            "hammer",
            "kitchen glove",
            "handle",
            "personal hygiene product",
            "duster",
            "robot vaccuum cleaner",
            "chain",
            "soap dish",
            "cereal box",
            "door window",
            "elephant toy",
            "frisbee",
            "cream tube",
            "folder holder",
            "internet socket",
            "moka pot",
            "stereo box",
            "face mask",
            "bunny chocolate",
            "magazine collector",
            "green vegetables",
            "shower holder",
            "toilet brush",
            "oven glove",
            "shower drain",
            "penholder",
            "switch board",
            "coffee pot",
            "marker eraser",
            "squeegee",
            "onions",
            "spray",
            "game cd box",
            "table clock",
            "apple",
            "spool",
            "portable speaker",
            "guitar pedal",
            "bread",
            "glass jar",
            "paper puncher",
            "dishwashing sponge",
            "shower hose",
            "surface cleaning liquid",
            "wallet",
            "circuit box",
            "toiletry",
            "hair brush",
            "headphone bag",
            "paper packages",
            "metal saw",
            "power adapter",
            "wlan router",
            "plant pot coaster",
            "oven mitt",
            "hanging light",
            "kitchen object",
            "machine button",
            "vanity light",
            "flush plate",
            "coasters",
            "leaf fan",
            "punching machine",
            "window handle",
            "light switches",
            "wine bottle",
            "tennis cap",
            "chips can",
            "food pot",
            "hand washing soap dispenser",
            "sockets",
            "wall light",
            "wet wipes",
            "detergent bag",
            "glasses cover",
            "hangbag",
            "bottle spray",
            "kitchen tap",
            "knob",
            "figurine",
            "hand vacuum",
            "potted plant",
            "weights",
            "marker storage",
            "mixing bowl",
            "power supply",
            "intercom screen",
            "coffee mug",
            "drilling machine",
            "electric socket",
            "hand shower handle",
            "hole punch",
            "silicon gun",
            "document holder",
            "wooden chest",
            "cheese",
            "jars",
            "headphones case",
            "measuring spoon",
            "monitor light",
            "ear muffs",
            "night lamp",
            "wall handle",
            "intercom device",
            "lanyard",
            "rugby ball",
            "shower loofah",
            "cable socket",
            "cleaning cloth",
            "dish washer soap",
            "magnets",
            "power brick",
            "coffee",
            "monitor base",
            "mushroom lamp",
            "trivet",
            "surface cleaner",
            "toiletry bottle",
            "paper note",
            "strainer",
            "colander",
            "kitchen brush",
            "multi socket",
            "radiator pipes",
            "saucer",
            "scissor",
            "stamp",
            "emergency button",
            "toilet brush holder",
            "coffee jar",
            "deodorant",
            "shower rod",
            "wet tissue",
            "tissue paper roll",
            "funnel",
            "oragnizer",
            "toilet plunger",
            "tumbler",
            "door knob",
            "coarser",
            "postit note",
            "punching tool",
            "beverage can",
            "dish",
            "star",
            "flask",
            "in-table power socket",
            "laptop charger",
            "wall intercom",
            "flour bag",
            "blowtorch",
            "cleaner",
            "takeout box",
            "hand soap",
            "hard drive",
            "straws",
            "monitor holder",
            "soldering iron",
            "control switch",
            "drainage",
            "box lid",
            "playstation controller",
            "shaving foam",
            "guitar stand",
            "toilet cleaner",
            "co detector",
            "covered power socket",
            "spray can",
            "tooth brush",
            "phone tripod",
            "bluetooth speaker",
            "paper rolls",
            "shelves",
            "dish washing liquid",
            "powerbank",
            "dried plant",
            "shampoo",
            "sticky note",
            "toilet seat brush",
            "dishwashing soap",
            "lan port",
            "scrubber",
            "tissues",
            "cord",
            "ashtray",
            "handle bar",
            "speakers",
            "dongle",
            "liquid soap",
            "mobile phone",
            "bunny decoration",
            "palm rest",
            "stream deck",
            "blinds chain",
            "dishwashing liquid",
            "hammer holder",
            "hand washing liquid",
            "shower wiper",
            "duct tape",
            "valve",
            "glove",
            "stationery",
            "ceiling speaker",
            "holder",
            "power plug",
            "wall speaker",
            "card",
            "electrical tape",
            "pot cover",
            "razor",
            "barcode scanner",
            "lotion",
            "eggs",
            "grab rail",
            "hairbrush",
            "lint roller",
            "post-it",
            "switches",
            "dusting cloth",
            "glue bottle",
            "handwash",
            "network outlet",
            "card reader",
            "cardboard boxes",
            "kitchen light",
            "paper notes",
            "pc charger",
            "product dispenser bottle",
            "hair dryer holder",
            "screwdriver",
            "shower squeegee",
            "juice tetrapack",
            "pliers",
            "sunblock",
            "bed sheet",
            "whiteboard pens",
            "fruits",
            "hook",
            "headphone holder",
            "light bulb",
            "weight plates",
            "ladle",
            "bar soap",
            "button",
            "dish brush",
            "toy car",
            "note",
            "post it",
            "sponge cloth",
            "wood stick",
            "light switchs",
            "paper weight",
            "product tube",
            "cell phone",
            "smartphone",
            "comb",
            "jump rope",
            "lan",
            "wireless charger",
            "door stopper",
            "cigarette packet",
            "pencil",
            "soap holder",
            "electrical plug",
            "toilet holder",
            "mask",
            "pocket calculator",
            "cabbage",
            "spoon",
            "doorknob",
            "fan switch",
            "rubber duck",
            "backdrop hook",
            "table tennis racket",
            "oven controls",
            "receipt",
            "soap bar",
            "tape roll",
            "tooth paste",
            "electrical adapter",
            "probe",
            "highlighter",
            "correction fluid",
            "dispenser",
            "pi̇cture",
            "door hinge",
            "whiteboard marker holder",
            "botttle",
            "decoration pieces",
            "power outlet",
            "towel hanger",
            "whiteboard duster",
            "magnet",
            "sticker",
            "nose spray",
            "flushes",
            "vertical blind control",
            "razor blade",
            "post it note",
            "wireless headphones",
            "cabinet top",
            "cream bottle",
            "datashow socket",
            "earbuds",
            "cabinet door",
            "chair cushion",
            "cosmetic tube",
            ]
            self.classes.append('removed')
            self.classes.append('split')
            self.cat_ids = np.array(np.arange(1, 3 + len(self.classes)))
        elif self.dataset == 'scannet200':
            self.classes = [
                'chair', 'table', 'door', 'couch', 'cabinet', 'shelf', 'desk',
                'office chair', 'bed', 'pillow', 'sink', 'picture', 'window',
                'toilet', 'bookshelf', 'monitor', 'curtain', 'book',
                'armchair', 'coffee table', 'box', 'refrigerator', 'lamp',
                'kitchen cabinet', 'towel', 'clothes', 'tv', 'nightstand',
                'counter', 'dresser', 'stool', 'cushion', 'plant', 'ceiling',
                'bathtub', 'end table', 'dining table', 'keyboard', 'bag',
                'backpack', 'toilet paper', 'printer', 'tv stand',
                'whiteboard', 'blanket', 'shower curtain', 'trash can',
                'closet', 'stairs', 'microwave', 'stove', 'shoe',
                'computer tower', 'bottle', 'bin', 'ottoman', 'bench', 'board',
                'washing machine', 'mirror', 'copier', 'basket', 'sofa chair',
                'file cabinet', 'fan', 'laptop', 'shower', 'paper', 'person',
                'paper towel dispenser', 'oven', 'blinds', 'rack', 'plate',
                'blackboard', 'piano', 'suitcase', 'rail', 'radiator',
                'recycling bin', 'container', 'wardrobe', 'soap dispenser',
                'telephone', 'bucket', 'clock', 'stand', 'light',
                'laundry basket', 'pipe', 'clothes dryer', 'guitar',
                'toilet paper holder', 'seat', 'speaker', 'column', 'bicycle',
                'ladder', 'bathroom stall', 'shower wall', 'cup', 'jacket',
                'storage bin', 'coffee maker', 'dishwasher',
                'paper towel roll', 'machine', 'mat', 'windowsill', 'bar',
                'toaster', 'bulletin board', 'ironing board', 'fireplace',
                'soap dish', 'kitchen counter', 'doorframe',
                'toilet paper dispenser', 'mini fridge', 'fire extinguisher',
                'ball', 'hat', 'shower curtain rod', 'water cooler',
                'paper cutter', 'tray', 'shower door', 'pillar', 'ledge',
                'toaster oven', 'mouse', 'toilet seat cover dispenser',
                'furniture', 'cart', 'storage container', 'scale',
                'tissue box', 'light switch', 'crate', 'power outlet',
                'decoration', 'sign', 'projector', 'closet door',
                'vacuum cleaner', 'candle', 'plunger', 'stuffed animal',
                'headphones', 'dish rack', 'broom', 'guitar case',
                'range hood', 'dustpan', 'hair dryer', 'water bottle',
                'handicap bar', 'purse', 'vent', 'shower floor',
                'water pitcher', 'mailbox', 'bowl', 'paper bag', 'alarm clock',
                'music stand', 'projector screen', 'divider',
                'laundry detergent', 'bathroom counter', 'object',
                'bathroom vanity', 'closet wall', 'laundry hamper',
                'bathroom stall door', 'ceiling light', 'trash bin',
                'dumbbell', 'stair rail', 'tube', 'bathroom cabinet',
                'cd case', 'closet rod', 'coffee kettle', 'structure',
                'shower head', 'keyboard piano', 'case of water bottles',
                'coat rack', 'storage organizer', 'folded chair', 'fire alarm',
                'power strip', 'calendar', 'poster', 'potted plant', 'luggage',
                'mattress'
            ]
            self.cat_ids = np.array([
                2, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 21,
                22, 23, 24, 26, 27, 28, 29, 31, 32, 33, 34, 35, 36, 38, 39, 40,
                41, 42, 44, 45, 46, 47, 48, 49, 50, 51, 52, 54, 55, 56, 57, 58,
                59, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76,
                77, 78, 79, 80, 82, 84, 86, 87, 88, 89, 90, 93, 95, 96, 97, 98,
                99, 100, 101, 102, 103, 104, 105, 106, 107, 110, 112, 115, 116,
                118, 120, 121, 122, 125, 128, 130, 131, 132, 134, 136, 138,
                139, 140, 141, 145, 148, 154, 155, 156, 157, 159, 161, 163,
                165, 166, 168, 169, 170, 177, 180, 185, 188, 191, 193, 195,
                202, 208, 213, 214, 221, 229, 230, 232, 233, 242, 250, 261,
                264, 276, 283, 286, 300, 304, 312, 323, 325, 331, 342, 356,
                370, 392, 395, 399, 408, 417, 488, 540, 562, 570, 572, 581,
                609, 748, 776, 1156, 1163, 1164, 1165, 1166, 1167, 1168, 1169,
                1170, 1171, 1172, 1173, 1174, 1175, 1176, 1178, 1179, 1180,
                1181, 1182, 1183, 1184, 1185, 1186, 1187, 1188, 1189, 1190,
                1191
            ])
        else:
            self.classes = [
                'cabinet', 'bed', 'chair', 'sofa', 'table', 'door', 'window',
                'bookshelf', 'picture', 'counter', 'desk', 'curtain',
                'refrigerator', 'showercurtrain', 'toilet', 'sink', 'bathtub',
                'garbagebin'
            ]
            self.cat_ids = np.array([
                3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 16, 24, 28, 33, 34, 36, 39
            ])

        self.cat2label = {cat: self.classes.index(cat) for cat in self.classes}
        self.label2cat = {self.cat2label[t]: t for t in self.cat2label}
        self.cat_ids2class = {
            nyu40id: i
            for i, nyu40id in enumerate(list(self.cat_ids))
        }
        assert split in ['train', 'val', 'test']
        if self.dataset == 'scannet' or self.dataset == 'scannet200':
            split_file = osp.join(self.root_dir, 'meta_data',
                              f'scannetv2_{split}.txt')
        else:
            split_file = osp.join(self.root_dir,
                              f'nvs_sem_{split}.txt')
        mmengine.check_file_exist(split_file)
        self.sample_id_list = mmengine.list_from_file(split_file)
        self.test_mode = (split == 'test')

    def __len__(self):
        return len(self.sample_id_list)

    def get_aligned_box_label(self, idx):
        box_file = osp.join(self.root_dir, 'scannet_instance_data',
                            f'{idx}_aligned_bbox.npy')
        mmengine.check_file_exist(box_file)
        return np.load(box_file)

    def get_unaligned_box_label(self, idx):
        box_file = osp.join(self.root_dir, 'scannet_instance_data',
                            f'{idx}_unaligned_bbox.npy')
        mmengine.check_file_exist(box_file)
        return np.load(box_file)

    def get_axis_align_matrix(self, idx):
        matrix_file = osp.join(self.root_dir, 'scannet_instance_data',
                               f'{idx}_axis_align_matrix.npy')
        mmengine.check_file_exist(matrix_file)
        return np.load(matrix_file)

    def get_images(self, idx):
        paths = []
        path = osp.join(self.root_dir, 'posed_images', idx)
        for file in sorted(os.listdir(path)):
            if file.endswith('.jpg'):
                paths.append(osp.join('posed_images', idx, file))
        return paths

    def get_extrinsics(self, idx):
        extrinsics = []
        path = osp.join(self.root_dir, 'posed_images', idx)
        for file in sorted(os.listdir(path)):
            if file.endswith('.txt') and not file == 'intrinsic.txt':
                extrinsics.append(np.loadtxt(osp.join(path, file)))
        return extrinsics

    def get_intrinsics(self, idx):
        matrix_file = osp.join(self.root_dir, 'posed_images', idx,
                               'intrinsic.txt')
        mmengine.check_file_exist(matrix_file)
        return np.loadtxt(matrix_file)

    def get_infos(self, num_workers=4, has_label=True, sample_id_list=None):
        """Get data infos.

        This method gets information from the raw data.

        Args:
            num_workers (int, optional): Number of threads to be used.
                Default: 4.
            has_label (bool, optional): Whether the data has label.
                Default: True.
            sample_id_list (list[int], optional): Index list of the sample.
                Default: None.

        Returns:
            infos (list[dict]): Information of the raw data.
        """

        def process_single_scene(sample_idx):
            print(f'{self.split} sample_idx: {sample_idx}')
            info = dict()
            pc_info = {'num_features': 6, 'lidar_idx': sample_idx}
            info['point_cloud'] = pc_info
            pts_filename = osp.join(self.root_dir, 'scannet_instance_data',
                                    f'{sample_idx}_vert.npy')
            points = np.load(pts_filename)
            mmengine.mkdir_or_exist(osp.join(self.save_path, 'points'))
            points.tofile(
                osp.join(self.save_path, 'points', f'{sample_idx}.bin'))
            info['pts_path'] = osp.join('points', f'{sample_idx}.bin')

            sp_filename = osp.join(self.root_dir, 'scannet_instance_data',
                                    f'{sample_idx}_sp_label.npy')
            super_points = np.load(sp_filename)
            mmengine.mkdir_or_exist(osp.join(self.save_path, 'super_points'))
            super_points.tofile(
                osp.join(self.save_path, 'super_points', f'{sample_idx}.bin'))
            info['super_pts_path'] = osp.join('super_points', f'{sample_idx}.bin')

            # update with RGB image paths if exist
            if os.path.exists(osp.join(self.root_dir, 'posed_images')):
                info['intrinsics'] = self.get_intrinsics(sample_idx)
                all_extrinsics = self.get_extrinsics(sample_idx)
                all_img_paths = self.get_images(sample_idx)
                # some poses in ScanNet are invalid
                extrinsics, img_paths = [], []
                for extrinsic, img_path in zip(all_extrinsics, all_img_paths):
                    if np.all(np.isfinite(extrinsic)):
                        img_paths.append(img_path)
                        extrinsics.append(extrinsic)
                info['extrinsics'] = extrinsics
                info['img_paths'] = img_paths

            if not self.test_mode:
                pts_instance_mask_path = osp.join(
                    self.root_dir, 'scannet_instance_data',
                    f'{sample_idx}_ins_label.npy')
                pts_semantic_mask_path = osp.join(
                    self.root_dir, 'scannet_instance_data',
                    f'{sample_idx}_sem_label.npy')

                pts_instance_mask = np.load(pts_instance_mask_path).astype(
                    np.int64)
                pts_semantic_mask = np.load(pts_semantic_mask_path).astype(
                    np.int64)

                mmengine.mkdir_or_exist(
                    osp.join(self.save_path, 'instance_mask'))
                mmengine.mkdir_or_exist(
                    osp.join(self.save_path, 'semantic_mask'))

                pts_instance_mask.tofile(
                    osp.join(self.save_path, 'instance_mask',
                             f'{sample_idx}.bin'))
                pts_semantic_mask.tofile(
                    osp.join(self.save_path, 'semantic_mask',
                             f'{sample_idx}.bin'))

                info['pts_instance_mask_path'] = osp.join(
                    'instance_mask', f'{sample_idx}.bin')
                info['pts_semantic_mask_path'] = osp.join(
                    'semantic_mask', f'{sample_idx}.bin')

            if has_label:
                annotations = {}
                # box is of shape [k, 6 + class]
                aligned_box_label = self.get_aligned_box_label(sample_idx)
                unaligned_box_label = self.get_unaligned_box_label(sample_idx)
                annotations['gt_num'] = aligned_box_label.shape[0]
                if annotations['gt_num'] != 0:
                    aligned_box = aligned_box_label[:, :-1]  # k, 6
                    unaligned_box = unaligned_box_label[:, :-1]
                    classes = aligned_box_label[:, -1]  # k
                    annotations['name'] = np.array([
                        self.label2cat[self.cat_ids2class[classes[i]]]
                        for i in range(annotations['gt_num'])
                    ])
                    # default names are given to aligned bbox for compatibility
                    # we also save unaligned bbox info with marked names
                    annotations['location'] = aligned_box[:, :3]
                    annotations['dimensions'] = aligned_box[:, 3:6]
                    annotations['gt_boxes_upright_depth'] = aligned_box
                    annotations['unaligned_location'] = unaligned_box[:, :3]
                    annotations['unaligned_dimensions'] = unaligned_box[:, 3:6]
                    annotations[
                        'unaligned_gt_boxes_upright_depth'] = unaligned_box
                    annotations['index'] = np.arange(
                        annotations['gt_num'], dtype=np.int32)
                    annotations['class'] = np.array([
                        self.cat_ids2class[classes[i]]
                        for i in range(annotations['gt_num'])
                    ])
                axis_align_matrix = self.get_axis_align_matrix(sample_idx)
                annotations['axis_align_matrix'] = axis_align_matrix  # 4x4
                info['annos'] = annotations
            return info

        sample_id_list = sample_id_list if sample_id_list is not None \
            else self.sample_id_list
        with futures.ThreadPoolExecutor(num_workers) as executor:
            infos = executor.map(process_single_scene, sample_id_list)
        return list(infos)
